model:
  model_name: bert-base-uncased
  num_experts: 2
  moe_hidden_dim: 512
  lora_rank: 4
  num_classes: 2
  lr: 5e-5 

training:
  rounds: 1
  local_epochs: 1
  batch_size: 2

clients:
  - name: FedAvg
    class: FedAvgClient
  - name: LMFed
    class: LMFedClient
  - name: FedProx
    class: FedProxClient
  - name: LoRAFed
    class: LoRAFedClient
  - name: FedMoE
    class: FedMoEClient
  - name: Scaffold
    class: ScaffoldClient

server:
  default_class: FLServer
  scaffold_class: ScaffoldServer

logging:
  save_dir: results
  tensorboard_dir: runs